### ISSUE TITLE
This project requires the 'OculusXR' plugin

### ISSUE THREAD

**Issue by DomCoccorese** [oculus-samples/Unreal-MRUtilityKitSample#7] opened 2024-11-14 13:54 UTC
Hello
Sorry but I can't start the sample. I followed the instructions reported in the Readme, but, when I launch the sample, it shows the following:

_This project requires the 'OculusXR' plugin, which could not be found. Would you like to disable it and continue?_

I also tried to disable OculusXR and compile the sample from source, but the project simply doesn't load (it freezes on the loading screen)

**Comment by DomCoccorese** [comment] 2024-11-19 08:09
Hello, thanks for the answer
I followed what you suggested. Specifically I copied the MetaXR folder from UE_5.4/Engine/Plugins/Marketplace/MetaXR to Unreal-MRUtilityKitSample-main\Plugins. Then, when I launch the project, it asks me to rebuild the following modules:

![immagine](https://github.com/user-attachments/assets/78fab9cf-357c-4ce0-bae3-f5ee3146eb07)

I clicked on Yes, and the rebuild process appears to finalize without problems. Unfortunately, after the rebuild, the UE editor crashes during loading. 

![immagine](https://github.com/user-attachments/assets/412c189a-65ef-4a57-bee8-ffba6927d1dc)

Here it is the entire log:

LoginId:e4bad5464cf64dba468f77a992b22076
EpicAccountId:66fe614a21f34963ab5f25ea37878ca0

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000058

openxr_loader
openxr_loader
openxr_loader
ViveOpenXRMR
ViveOpenXRFacialTracking
OVRPlugin
OVRPlugin
OVRPlugin
UnrealEditor_OculusXRHMD!FOculusXRHMDModule::PreInit() [C:\Users\domco\Documents\Unreal Projects\Unreal-MRUtilityKitSample-main\Plugins\MetaXR\Source\OculusXRHMD\Private\OculusXRHMDModule.cpp:201]
UnrealEditor_OculusXRHMD!OculusXRHMD::FOculusXRHMD::InitializeSession() [C:\Users\domco\Documents\Unreal Projects\Unreal-MRUtilityKitSample-main\Plugins\MetaXR\Source\OculusXRHMD\Private\OculusXRHMD.cpp:2964]
UnrealEditor_OculusXRHMD!OculusXRHMD::FOculusXRHMD::InitDevice() [C:\Users\domco\Documents\Unreal Projects\Unreal-MRUtilityKitSample-main\Plugins\MetaXR\Source\OculusXRHMD\Private\OculusXRHMD.cpp:3054]
UnrealEditor_OculusXRHMD!OculusXRHMD::FSplash::Startup() [C:\Users\domco\Documents\Unreal Projects\Unreal-MRUtilityKitSample-main\Plugins\MetaXR\Source\OculusXRHMD\Private\OculusXRHMD_Splash.cpp:163]
UnrealEditor_OculusXRHMD!OculusXRHMD::FOculusXRHMD::Startup() [C:\Users\domco\Documents\Unreal Projects\Unreal-MRUtilityKitSample-main\Plugins\MetaXR\Source\OculusXRHMD\Private\OculusXRHMD.cpp:2833]
UnrealEditor_OculusXRHMD!FOculusXRHMDModule::CreateTrackingSystem() [C:\Users\domco\Documents\Unreal Projects\Unreal-MRUtilityKitSample-main\Plugins\MetaXR\Source\OculusXRHMD\Private\OculusXRHMDModule.cpp:354]
UnrealEditor_Engine!UEngine::InitializeHMDDevice() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:3873]
UnrealEditor_Engine!UEngine::Init() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:2026]
UnrealEditor_UnrealEd!UEditorEngine::InitEditor() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:839]
UnrealEditor_UnrealEd!UEditorEngine::Init() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1191]
UnrealEditor_UnrealEd!UUnrealEdEngine::Init() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:96]
UnrealEditor!FEngineLoop::Init() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4876]
UnrealEditor_UnrealEd!EditorInit() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdGlobals.cpp:112]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:158]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:118]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:258]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:298]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by DomCoccorese** [comment] 2024-11-22 09:24
Update: Found solution thanks to UE Forum support.
For anyone facing the issue reported above (Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000058). The problem is due to some active OpenXR API layers that can mess with MetaXR. You can disable them both by SteamVR as well as by using this tool (recommend):

https://github.com/fredemmott/OpenXR-API-Layers-GUI

**Comment by gabryelx** [comment] 2024-11-22 17:50
Thanks for digging into it, I get a lot of random crashes with the MRUK, this might be related, so I'll give it a try.

**Comment by felixweilbach** [comment] 2024-11-22 19:01
@DomCoccorese glad you found a solution. @gabryelx If you manage to have steps to reproduce the crashes I'm happy to dig into them.

**Comment by gabryelx** [comment] 2024-11-25 16:37
@felixweilbach Thank you, I will try and find a pattern.  Right now it seems to be occasionally when I enter VRPIE, it will lead to a random crash related to the OculusHMD.  I haven't had this issue with non-MRUK projects but I will try and narrow it down.

**Comment by felixweilbach** [comment] 2024-11-26 10:07
ok, I will close this issue for now. Please report any issues you find.

**Closed by felixweilbach** 2024-11-26 10:07 UTC

**Comment by gabryelx** [comment] 2024-11-26 17:22
Just had that crash again, entering VRPIE, 2 player listen server mode.  It might not be related to MRUK, but as mentioned it's new to this project so I'm not sure.  This happens maybe 1 in 10 times of entering VRPIE in networked mode.

![image](https://github.com/user-attachments/assets/33fe313a-98f3-4756-981d-33eb2c5d9561)

**Comment by felixweilbach** [comment] 2024-12-04 13:10
Thanks @gabryelx. Do you have any steps to reproduce the issue? Otherwise will be hard to investigate.

**Comment by gabryelx** [comment] 2024-12-04 18:48
I don't, other than VRPIE and networked play mode... I will attempt to repro it with a fresh project with MRUK soon though.
